project:
  type: website

execute: 
  freeze: auto

filters: 
  - embedio

website:
  title: "Brady's Blog"
  google-analytics: G-T4ZHBLFMQF
  draft-mode: unlinked

  navbar:
    right: 
      - about.qmd
      - text: "Blog"
        href: index.qmd
      - text: "Molecular Nodes"
        icon: arrow-up-short
        href: https://bradyajohnston.github.io/MolecularNodes
      - text: "Talks"
        href: talks/index.qmd
    left:
      - icon: github
        href: https://github.com/bradyajohnston
      - icon: youtube
        href: https://youtube.com/c/bradyjohnston
      - icon: twitter
        href: https://twitter.com/bradyajohnston
format:
  html:
    theme: 
      light: yeti
      dark: darkly
    css: styles.css



