---
title: Extensions on GitHub
author: Brady Johnston
date: 2025-09-20
format: 
  html: default
  revealjs: 
    theme: dracula
    output-file: slides.html
toc: true

draft: true
execute: 
  freeze: auto
  cache: true
---

:::: {.content-visible when-format="revealjs"}
<!-- will only appear in slides -->
## Contents

::: {.fragment}
- Who am I and what is Molecular Nodes?
:::
::: {.fragment}
- Add-on Development on Github
:::
::: {.fragment}
- Add-on Distribution on GitHub
:::
::::

## I’m Brady!

::: {.content-visible when-format="revealjs"}

- Biochemist & Biophysicist turned 3D Animator

- 2022 talk about Visualising Viruses

:::

<iframe id="ytplayer" type="text/html" width="800" height="450" src="https://www.youtube.com/embed/adhTmwYwOiA?autoplay=1?mute=1&origin=http://bradyajohnston.github.io" frameborder="0"></iframe>

::: {.content-visible unless-format="revealjs"}

Will only appear in HTML.

:::

## Molecular Nodes
quick overview of MN - show talk from last year etc
some fun example videos

::: {.content-visible when-format="revealjs"}
<!-- will only appear in slides -->
:::

::: {.content-visible unless-format="revealjs"}
<!-- will only appear in blogpost -->
:::

## Add-on & a Python Package?

::: {.content-visible when-format="revealjs"}
<!-- will only appear in slides -->
:::

::: {.content-visible unless-format="revealjs"}
> It's less likely than you'd think!

Creating an add-on for Blender that can also be built and shipping as a python package was quite the task. 
It leads to a variety of problems and strange engineering issues that come with writing code for Blender that a 'regular' python package wouldn't have to deal with. 

Covering that topic with all of our learnings would be a massive blog post itself. 
The short version is that you can install molecularnodes from [`pypi`](https://pypi.org/p/molecularnodes) and use if for molecular rendering in python scripts of jupyter notebooks like this one.

:::

```{python}
#| echo: true
#| label: fig-dna
#| fig-cap: X-ray crystallography structure of a fragment of DNA.
#| output-location: slide
# !pip install bpy molecularnodes

import molecularnodes as mn
canvas = mn.Canvas(
    engine=mn.scene.Cycles(samples=16),
    resolution=(1280, 720),
    transparent=True
    )

mol = mn.Molecule.fetch("1BNA")
mol.add_style("vdw")

canvas.frame_view(mol, (3.14, 3.14 / 2, 0))
canvas.snapshot()
```

## Building & Distributing MN
tested and built in GitHub actions
example yaml

## Useful Actions
setup-blender
build and distribute documentation

## Distributing your own Extensions
Details and built: https://bradyajohnston.github.io/extensions/
Subscribe with:

```bash
https://bradyajohnston.github.io/extensions/index.json
```



## How is it Built?

```yaml
name: Download Release Files

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-website:
    runs-on: macos-14
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: bradyajohnston/setup-blender@v2.1
        with: 
          version: 4.3.2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
            version: "latest"
    
      - name: Get Release Assets
        run: |
          uv run --with requests scripts/download.py
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Generate index.json
        run: |
            blender --command extension server-generate --repo-dir=repo
    
      - name: Quarto Render
        run: |
          uv run --with pyyaml quarto render
    
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
            target: gh-pages
            path: .
            render: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## How is it built?

```yaml
name: Download Release Files

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-website:
    runs-on: macos-14
    permissions: write-all
    steps:
      - uses: bradyajohnston/setup-blender@v2.1
        with: 
          version: 4.3.2
      - name: Get Release Assets
        run: |
          uv run --with requests scripts/download.py
      - name: Generate index.json
        run: |
            blender --command extension server-generate --repo-dir=repo
    
      - name: Quarto Render
        run: |
          uv run --with pyyaml quarto render
    
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
            target: gh-pages
            path: .
            render: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

::: {.content-visible when-format="revealjs"}
<!-- will only appear in slides -->
:::

::: {.content-visible unless-format="revealjs"}
<!-- will only appear in blogpost -->
:::