---
title: Making a Holographic Poster
subtitle: Proteins belong in the third dimesion.
author: Brady Johnston
date: 2023-08-30
---

IUCr2023 has wrapped up. It was an interesting and at times gruelingly long conference. I presented a poster, which finally gave me the chance to test out an idea that I've had for many years.


# The TL;DR

To quickly summarise the details, I attached both my iPad and a [Looking Glass Portrait](https://look.glass/brady) using extra-strong velcro tape to my poster. 
I had to ensure my poster was laminated, and that I added lots of extra velcro tape to the back of the poster (extra behind the iPad and display) to ensure it could take the weight. 
All of the movies played on the iPad were either screen-recordings of me working inside of Blender, or rendered movies that were created inside of Blender. 
All of the molecular data was imported and animated with [Molecular Nodes](https://github.com/bradyajohnston/MolecularNodes), the add-on which I created and which the poster was about.
The holograms were similarly imported and animated with Molecular Nodes, but the rendering was done with [AliceLG](https://github.com/regcs/AliceLG) add-on or with some of my own code.
These holograms were synced to the display, and the display played the pre-rendered movies. Power was supplied by a large battery bank, which was itself velcroed to the poster board. 
Nothing special about this battery bank, other than it was the biggest one I could buy and it could output up to 60 W over USB-C power delivery.

That’s the short description of everything that went into the poster. If you want to read on more about the thought process that went into creating it, continue on below. 


# Give me every detail

This was an idea that has been bouncing around inside my head for years. I am a structural biologist, and the field we work in is blessed that our data is usually just _beautiful_ to look at. Even with some of the earliest rendering techniques, the complexity, symmetry and otherworldiness of protein structures was an instant hook for so many structural biologists.

With academic posters, so much of creating a good poster is getting attendees to pay attention. You can’t tell colleagues about all of the cool research that you are doing, if nobody comes over to actually look at your poster in the first place. To this end, there is a lot of great resources about what goes in to making a great poster. If you are interested in making better posters, I would recommend the blog [Better Posters](http://betterposters.blogspot.com) as the best starting point. My own personal philosophy is that _less is more_. The best posters have minimal or no text at all. Figures reign supreme when it comes to making a poster. Even then, you don’t want to overwhelm viewers by packing in too many figures. Focus on the ones that support your key message and go with them, leave the rest for the paper.

In making my first couple of academic posters, I felt hindered in terms of describing large protein structures. They are an inherently 3D thing. Reducing them down to a 3D image is difficult. Depth-cueing with fog, cropping the specific areas and providing multiple views of the same thing are all ways to get around the limitations of 2D to describe a complex 3D molecule.

Others had previously used techniques like red / blue 3D, where the viewers can don 3D glasses to view the structure. This works with limited success. It limits your viewers to the number of glasses your brought with you, colours don’t translate super well, and viewing angles are similarly limited.

The most promising thing was looking at [_lenticular lenses_](https://en.wikipedia.org/wiki/Lenticular_lens). There were speciality sign printers who would do lenticular prints and ship you the print + lens to go on the poster, but this  was targeted to the similar idea as having a moving footballer on a collectible card. Having 3-4 conformations of a protein that would move as the viewer moved would be cool, but the price tag was too high for a PhD student on a budget, and the idea remained an idea.

## Looking Glass Portrait
Back in December 2020, there was a targeted ad on 
Facebook for a kickstarter campaign. In this case the targeted advertising dollars paid off, they had nailed their audience and I [pledged immediately](https://www.kickstarter.com/projects/lookingglass/looking-glass-portrait).

With shipping delays related to global microchip shortages and that one boat blocking that one canal_, it was a while before I finally got hands on with the display. I was unsure how the effect would translate to real life, as the 3D wasn’t immediately obvious when viewing through a video on a regular screen. When I finally got it, it worked great and I played around with a number of 